version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"

sphinx:
  configuration: docs/conf.py

formats:
  - epub

python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - docs
